### ISSUE TITLE
Unable to translate on-screen text which appears when clicking the start button

### ISSUE THREAD

**Issue by jocker-il** [Choumiko/FARL#10]
![farl on screen text](https://cloud.githubusercontent.com/assets/13031901/8895955/fc9c4224-33f4-11e5-9255-77b20ad4c988.GIF)

 and why is the frond one "last" ? shouldn't it be "front" ?

**Comment by Choumiko** [comment]
That's a good question.. Will change it to Front. As for translating it, this is actually an entity, not sure how that works. You can add an translation in it already.
Let's use:
text-front = Front
text-behind = Behind
there's also a S that appears over a signal, it's mostly there for debug and will eventually go away (perhaps the Front/Behind will to, but not as soon as the S)
I'll try localizing it Tuesday evening (Europe).

**Comment by jocker-il** [comment]
yes that's ok.

 just put those strings in the en.cfg and I'll copy them to the same line in the he.cfg

you seem have a system for string naming (does look good)
