### ISSUE TITLE
[3.0.0] maintaince mode changes surface tiles to grass

### ISSUE THREAD

**Issue by 0ptera** [Choumiko/FARL#100]
With maintenance mode enabled farl replaces everything with grass tiles:
![2019-03-05-13-52-28-7738097](https://user-images.githubusercontent.com/8436934/53806759-23ac3c80-3f4e-11e9-8051-a255eff89cfb.png)

The map was migrated from 0.16.
Other mods with possible interference Dectorio, NiceFill.

**Comment by Choumiko** [comment]
fixed in 998514783bb6dfdb3b628654b1c6a0937e054be4

it still messes up when removing concrete in maintenance mode, so i'm leaving it open
