### ISSUE TITLE
"-root mode" text that appears can't be translated

### ISSUE THREAD

**Issue by jocker-il** [Choumiko/FARL#11]
This error text is not translatable (I know it's just for negative-root, but it might be opened to other users some day (as we discussed) and it's bad practice, as I understand it (not judging !) to have hard-coded text strings)

![farl ngtv-root mode](https://cloud.githubusercontent.com/assets/13031901/8895961/70234e40-33f5-11e5-9f53-422e50fb2b7f.GIF)

**Comment by Choumiko** [comment]
-root mode is already useable by everyone. 
I think for the proper name i'm going with Car mode, for now please use text-error-root as the key, i'll add it in the code

**Comment by jocker-il** [comment]
I'd rather see how you put it in en locale - most of your strings have prefixes  Best Wishes The JoCKeR  

```
 On Monday, July 27, 2015 12:50 AM, Choumiko <notifications@github.com> wrote:
```

 -root mode is already useable by everyone. 
I think for the proper name i'm going with Car mode, for now please use text-error-root as the key, i'll add it in the code—

**Comment by Choumiko** [comment]
resolved in https://github.com/Choumiko/FARL/commit/0dcb698f873b27cbe5dc0d543744315242224162
