### ISSUE TITLE
wired,not related text appears in F.A.R.L. info

### ISSUE THREAD

**Issue by jocker-il** [Choumiko/FARL#17]
do you know where this comes from ?

![image](https://cloud.githubusercontent.com/assets/13031901/9021353/9678e0fa-3846-11e5-94b1-9bcbc276d471.png)

 Didn't find it in the files (made a windows search)...

**Comment by Choumiko** [comment]
That's a backer name. You also get this on vanilla locomotives, radars,etc

**Comment by jocker-il** [comment]
it just pushes itself into FARL info ? no way to get rid of it ?  Best Wishes The JoCKeR  

```
 On Saturday, August 1, 2015 1:19 PM, Choumiko <notifications@github.com> wrote:
```

 That's a backer name. You also get this on vanilla locomotives, radars,etc—

**Comment by Choumiko** [comment]
Not sure what you mean, in the picture F.A.R.L. is the name of the entity, NecoAngelus is the name of a backer.
If you place a normal locomotive you'll see Diesel locomotive NecoAngelus or another name. It's a vanilla thing

**Comment by jocker-il** [comment]
I know that train stops get backer names, didn't know trains do too... so I checked it and found out you where right :)
