### ISSUE TITLE
Placed rails do not respect the locomotive's force.

### ISSUE THREAD

**Issue by silasary** [Choumiko/FARL#23]
When a FARL places rails, it always uses game.forces.player, rather than inheriting the locomotive's force.
This causes issues in PvP games.

**Comment by Choumiko** [comment]
uh, thanks. I'll guess making the force either the same as FARL or the driver should be ok? I don't know much about pvp, can you drive a train/car from the enemy? If you can, what force should the tracks belong to?

**Comment by silasary** [comment]
You can drive an enemy's locomotive [assuming they haven't enabled a schedule].
It's probably best to copy from the FARL.

**Comment by Choumiko** [comment]
Great, that's what i already did in the latest commit. Next release is going to be a few days, but grabing the master.zip and renaming should do it i guess.
