### ISSUE TITLE
"Maintenance" text in gui not using locale string

### ISSUE THREAD

**Issue by jocker-il** [Choumiko/FARL#30]
not using the locale string for "Maintenance":

![farl not using locale text for maintenance](https://cloud.githubusercontent.com/assets/13031901/10439539/3a77c1dc-7143-11e5-97c0-5e6afc7a9766.jpg)

And there is also these two error messages:
![farl-no hebrew for changing modes msg](https://cloud.githubusercontent.com/assets/13031901/10439367/12e935ac-7142-11e5-92a0-08c776a2a7e5.JPG)

found this in "FARL.lua":

![farl no locale text for this](https://cloud.githubusercontent.com/assets/13031901/10439410/6249ce86-7142-11e5-9645-aa76460f813e.jpg)

and what does this do ?

![farl what those this do and is it localized](https://cloud.githubusercontent.com/assets/13031901/10439431/823531ea-7142-11e5-95ab-93941558baee.jpg)

love that you can add pictures to comments ( :D )

 sorry for adding issues - did some testing today for my hebrew updates and found these.

Thank you for this mod and the work you do :)

**Comment by Choumiko** [comment]
Thanks for telling me exactly where to look ;)
Fixed in the latest commit, not sure about the last one "maintenance1", looks like an old error made for debugging. If you ever see this while using FARL please report, but i think that error should never occur.

**Comment by jocker-il** [comment]
Right ? I was board enough to look for it... :)

 This also gives you a reason to integrate my latest translation strings and up the version ;)

Sent from Samsung Mobile.
