### ISSUE TITLE
EntityPrototype Smart train stop doesn't have an order string and there is no item to place it.

### ISSUE THREAD

**Issue by MachtigeMike** [Choumiko/FARL#44]
after updating to version 0.5.22 i get this error when loading the game
   2.276 Error Util.cpp:58: EntityPrototype Smart train stop doesn't have an order string and there is no item to place it.

> 0.776 Desktop composition is active.
>    0.874 Loading mod core 0.0.0 (data.lua)
>    0.876 Loading mod base 0.12.30 (data.lua)
>    0.943 Loading mod color-coding 1.0.7 (data.lua)
>    1.009 Loading mod EvoGUI 0.4.11 (data.lua)
>    1.067 Loading mod fluid-barrel 1.0.0 (data.lua)
>    1.128 Loading mod ModuleInserter 0.1.31 (data.lua)
>    1.191 Loading mod MoreBots 1.0.0 (data.lua)
>    1.244 Loading mod MoreLight 1.0.0 (data.lua)
>    1.299 Loading mod robotic-combinators 0.3.4 (data.lua)
>    1.363 Loading mod rso-mod 1.0.3 (data.lua)
>    1.415 Loading mod RSORadar 0.0.1 (data.lua)
>    1.472 Loading mod SmartTrains 0.3.81 (data.lua)
>    1.533 Loading mod Tape Measure 1.0.1 (data.lua)
>    1.597 Loading mod TheFatController 0.4.1 (data.lua)
>    1.650 Loading mod FARL 0.5.22 (data.lua)
>    1.714 Loading mod SmartTrains 0.3.81 (data-updates.lua)
>    1.768 Loading mod FARL 0.5.22 (data-updates.lua)
>    1.825 Loading mod ModuleInserter 0.1.31 (data-final-fixes.lua)
>    1.900 Loading mod FARL 0.5.22 (data-final-fixes.lua)
>    1.955 Checksum for core: 3711505753
>    1.955 Checksum for mod base: 2829195351
>    1.955 Checksum for mod blueprint-string: 0
>    1.955 Checksum for mod color-coding: 1896300273
>    1.955 Checksum for mod EvoGUI: 1040096666
>    1.955 Checksum for mod fluid-barrel: 3300501898
>    1.955 Checksum for mod ModuleInserter: 3558109661
>    1.955 Checksum for mod MoreBots: 245390645
>    1.955 Checksum for mod MoreLight: 926590685
>    1.955 Checksum for mod robotic-combinators: 1519654044
>    1.955 Checksum for mod rso-mod: 1069585066
>    1.955 Checksum for mod RSORadar: 2150377606
>    1.955 Checksum for mod SmartTrains: 2094610636
>    1.955 Checksum for mod Tape Measure: 284499724
>    1.955 Checksum for mod TheFatController: 334569396
>    1.955 Checksum for mod trainstats: 0
>    1.955 Checksum for mod FARL: 1759233608

**Comment by Choumiko** [comment]
fixed in https://github.com/Choumiko/SmartTrains/releases/tag/v0.3.81f
