### ISSUE TITLE
[request] Cement in Water

### ISSUE THREAD

**Issue by VasVadum** [Choumiko/FARL#46]
When placing tracks in water, cement should place cement floors in the water, not dirt.  Replace dirt with cement.  It would make a lot more sense.  Also, make sure you place a 2x2 cement block under the tracks, not beside.  As it stands, dirt is placed in t wrong spot so my tracks are half floating in water.  I know this can be done, because another mod places cement around water or in water just fine.

**Comment by Choumiko** [comment]
FARL uses landfill item when placing water since Factorio 0.13. If concrete paving is desired it can be used in the blueprint
