### ISSUE TITLE
Left turns for RHD don't work

### ISSUE THREAD

**Issue by Svish** [Choumiko/FARL#47]
I've tried to use the generated blueprints and then swapped the lights so they are correct. Going north goes ok, but if I turn left I get `Deactivated: Can't place track`.

Could you maybe attach a screenshot of pair of working right-hand-side 2-track blueprints?

**Comment by Choumiko** [comment]
I just tried it, looks like you found a bug. FARL seems to not like left turns for right hand side driving. Right turns are ok.
That's a (in theory) working RHD blueprint, which i guess you had: http://imgur.com/pT3PVZm

**Comment by Svish** [comment]
Ended up trying to use LHD for everything when I ran into the bug, so will be a pain to switch everything back now, but good to hear the bug wasn't just in my head :P

It seems to be an issue with turning when using LHD sometimes too though... not sure what happens really... but it fails to lay a track right after the turn. Not an enormous problem as I can lay the tiny rest of the turn manually and then activate FARL again, but yeah... maybe related to this bug?

**Comment by Svish** [comment]
Oh, and yes, the RHD blueprint you linked to looks pretty much like what I had. Just took the existing generated one and swapped the signals.

**Comment by Choumiko** [comment]
For me it was like this: LHD would fail when turning right, RHD failed when turning left
Should all be fixed in https://github.com/Choumiko/FARL/releases/tag/v0.5.25

**Comment by Svish** [comment]
Sounds about right actually. Thanks for fix!
