### ISSUE TITLE
Adding hebrew locale to FARL

### ISSUE THREAD

**Issue by jocker-il** [Choumiko/FARL#6]
I'd like to offer myself to make a hebrew locale to the project. I support this mod because I think it's great and wish to use it in my coming youtube series in hebrew.

 how can I make this happen ?

**Comment by Choumiko** [comment]
sure, just create a locale file for hebrew and make a pull request

**Comment by jocker-il** [comment]
made a sample file. need to convert it to hebrew - please inform me if you added any text to "en.cfg" file

**Comment by jocker-il** [comment]
I have some questions - what is "-root mode" ?

**Comment by Choumiko** [comment]
-root mode is more or less like a car, FARL places rails like normal, but removes them once it passed over them.  I'll propably rename it to car+ mode or something similar.

**Comment by jocker-il** [comment]
The other question was supposed to be where do you see it...

 so this option is like giving the player a vehicle to move fast on the map with ? that sounds good and bad... wonder if there is demand from the community for this feature. Anyway, I get the point, but I don't really know how to translate it :)

**Comment by Choumiko** [comment]
well, it was a request from a youtuber, haven't thought about balance. But you have a point there, could limit the speed when the mode is active. As for a name, i still don't know

**Comment by jocker-il** [comment]
Oh, I get it now - it was for negative root ? :smile: nice

**Comment by jocker-il** [comment]
I'm thinking leaving this issue as on going and linking my updated to it will give us a way to keep track of changes - @narc does the same thing in #EvoGui - What do you think ?

 anyway, I'v updated Hebrew locale to 0.4.41

**Comment by Choumiko** [comment]
that works for me. I'll try to remember referncing this when i addd a new locale key.

**Comment by Choumiko** [comment]
See #82, makes things easier for me
