### ISSUE TITLE
Add support for lighted electric poles

### ISSUE THREAD

**Issue by ghost** [Choumiko/FARL#60]
I just published my lighted electric poles mod to the portal (https://mods.factorio.com/mods/missamo80/LightedElectricPoles). In order for it to work properly with FARL I'd like to request a small modification to FARL.lua, as was done for the Concrete Lamppost. The following change is necessary:

trigger_event = {
  ["concrete-lamppost"] = true,
  ["big-electric-pole"] = true,
  ["lighted-small-electric-pole"] = true,
  ["lighted-big-electric-pole"] = true,
  ["lighted-medium-electric-pole"] = true,
  ["lighted-substation"] = true
}

I've confirmed locally that this modification results in the lighted electric poles getting placed properly by FARL. Thanks!

**Comment by Choumiko** [comment]
I was following the discussion on the forums and just was about to reply. I might do some other changes, that let's mods register entitys via a remote interface (and/or create the events for poles by default as poles get placed not as often as rails/walls etc with FARL)
But yes, i'll add your entities in the next update

**Comment by ghost** [comment]
Thanks! If you want to try the remote interface route let me know over in the forums via PM and I can try wiring it up.

**Comment by Choumiko** [comment]
I added the interface in 9588e003bc0bbc90ef65c41d27f86c73bbc4d9e4
But FARL now raises the events by default for all poles, so it's not necessary for your mod

**Comment by ghost** [comment]
I confirmed yesterday that my poles are getting placed correctly with the latest update. Thanks!
