### ISSUE TITLE
Farl won't read blueprints on 4th toolbar row

### ISSUE THREAD

**Issue by Nexela** [Choumiko/FARL#61]
2 Blueprints on toolbar both have bobs mk4 poles (previous working bp a few versions ago had mk3)

When clicking read blueprints the settings window just closes without a message blueprints won't update

**Comment by Choumiko** [comment]
All three Mk4 variants (big, medium pole, substation) work for me.
Blueprintstring/screenshots of the blueprints please

**Comment by Nexela** [comment]
I have narrowed it down. Farl won't read blueprints on the 4th (bottom) toolbar, moving the blueprints to any other row causes it be read correctly.
