### ISSUE TITLE
Request auto/manual switch

### ISSUE THREAD

**Issue by Nexela** [Choumiko/FARL#62]
I would find a Small button at the top of the farl control panel to toggle between automatic and manual control of the train a sweet quality of life improvement!

P.S Awesome work on some of the latest additions, the remote.calls, Farl module, and Ghost following are just awesome on top of an already awesome mod!

**Comment by Choumiko** [comment]
Hm, not sure where to put it in the GUI, i like the fact that at the moment the gui is relatively small. Adding a button labeled "Automatic"/"Manual" to the left of the buttons/in a second row would increase it. 
If you don't mind the honking: https://mods.factorio.com/mods/GotLag/Honk adds a hotkey to toggle between automatic/manual (I guess i could add a hotkey if Honk is not installed)

The ghost following still needs a lot of work, ultimately i want FARL to be able to drive from a depot to the construction site, follow the ghosts and return to depot when done or when out of materials. And after that i'll wait for complaints about performance from players running FARL in all directions at once :-D
