### ISSUE TITLE
Train "Item" Prototype doesn't save equipment

### ISSUE THREAD

**Issue by Nexela** [Choumiko/FARL#63]
I believe the only fix needed is to change the type from "item" to "item-with-entity-data"

related: https://forums.factorio.com/viewtopic.php?f=61&t=9470&p=230252&hilit=farl#p230252

**Comment by Choumiko** [comment]
Yeah, seems like changing the item type is enough. Fixed with f378c4e442d8c31a05b5c04232cbd4f13ea5aabb
