### ISSUE TITLE
Deleting FARL while inside does not remove GUI

### ISSUE THREAD

**Issue by aleedom** [Choumiko/FARL#72]
I have only seen this bug in 0.15.X.  

Be in a stopped FARL with no attached cars.  Right click the FARL to remove it.  Notice that the GUI is still open.  

The save I experience this on has full angels and bobs with some utility mods, so I cannot verify that the cause is from the mod itself or from one of them.  

Thank you for creating and maintaining this wonderful mod!

**Comment by Choumiko** [comment]
Thanks for the report, fixed in e86c408f31f1f1f24db636f2c054170656b3df6a
