### ISSUE TITLE
FARL 1.0.9 - Bugged recipe for inserters

### ISSUE THREAD

**Issue by searker** [Choumiko/FARL#76]
With version 1.0.9, a bugged recipe for inserters was introduced. It requires insane amounts of resources.

Switching back to 1.0.8 fixed the issue, however i had to disable FARL, save my map and re-enable it to reset the "recipe-cache" since Factorio was still thinking that upgraded inserters (fast, stack, etc.) would require the expensive normal inserter.

**Comment by wjzijderveld** [comment]
I noticed the same thing, although I can just create upgrades with the vanilla inserters as ingredient.
