### ISSUE TITLE
Unexpected error when laying rail

### ISSUE THREAD

**Issue by sgtsquiggs** [Choumiko/FARL#83]
Loaded up my train with brick, rail, lamps, poles, signals, etc. Loaded up these two blueprints:

```
0eNqdle9ugyAUxd/lfpZFAW3nqyzLQu1NS4JokG5rGt99+GeuVruA30S5v3Pu4UZucFAXrI3UFvIbyKLSDeRvN2jkSQvVvbPXGiEHabGECLQou5URUkEbgdRH/IY8ad8jQG2llTjU94vrh76UBzRuw1T5VVVH1KQ4Y2Mdr64aV1TpTsmBCH9JI7gOD20bLUB0AjXWmTidLem9LEl04FDn8igNFsO33QqTzdpy1oTUZAxgyU1+HbqHOTtdYfOJfZAngsrtNbIgdaVwyY5H8Frj6V/jpVCKKFHWS8Jkjq7Hl3lRph7jdcpuHtizqOI7yiyoZIW59z3Y4Vw9jvXVc+bYaJN1zbo5tlKNQ/wYy5ht183ktdJIamHP0Dl4UsC9C3ioAt+owLwLWKgC26hAvQtoqALdqJB4FyShCsk2hdh3fxzIj7fgvemB5pMtdO/s6SPd3XqFQYvPNweyvSeThdHZf3T36+ov6fzuTo/gE03TAzLOabrfp9lr1rY/g8eQEA==
```
```
0eNqVl+FugyAUhd+F39IIAlpfZVkWa0lLgmiUbmsa331ou85O3Xr+id57PN/l5qIXsrMn3bTGeZJfiClr15H85UI6c3CFHe75c6NJTozXFYmIK6ph1RbGkj4ixu31J8lZ/xoR7bzxRl/zx8X5zZ2qnW5DwD2zqwprqS2qJqg1dRdSaje8J8jQeCMjcg4XbCP7PprJ8LvMR13vtaPlUXd+LiT/0Ul+7PiAcjh6OhLNHYlRJ14SEQ/VCFYK4+itbnMh/m0pMIbC7U2ry+tzsaAt79o7c6DahtjWlLSprV7QZusm1aPJNXvx1N2CTPpswfi6lezJzaPpzczK5m2f6yU2VQnt6Y299ebvyOyKzvsJZO00bQp/JIOBlQQGJsRg/PP6KUqQogQpSJCCBAolUCiBAgkUSCBRAokSSJBAggQCJRAogQAJBEiQoAQJSpCABAlIwFECjhJwkICDBAwlYCgBAwkYRhCDADHoP8bsx5h7tPxo9cHig7VH2x/tfrD5wd5Hxw86fcDhA84edPyj0x8c/uDsR49f9PQFD98/z97wNTr+TuWTv6+IvOu2GwWUEFxmmVRb1fdfuZJdgw==
```

It starts to knock down trees and removes a few things that were in the way, then it errors and stops working.

```
1552.903 Script control.lua:516: stack traceback:
	__FARL__/control.lua:516: in function 'debugDump'
	__FARL__/control.lua:124: in function <__FARL__/control.lua:88>
	[C]: in function 'pcall'
	__FARL__/control.lua:88: in function <__FARL__/control.lua:87>
1552.903 Script control.lua:517: 6979587 Unexpected error: __FARL__/FARL.lua:2783: attempt to index field '?' (a nil value)
1565.455 Script control.lua:516: stack traceback:
	__FARL__/control.lua:516: in function 'debugDump'
	__FARL__/control.lua:124: in function <__FARL__/control.lua:88>
	[C]: in function 'pcall'
	__FARL__/control.lua:88: in function <__FARL__/control.lua:87>
1565.455 Script control.lua:517: 6980340 Unexpected error: __FARL__/FARL.lua:2783: attempt to index field '?' (a nil value)
1570.906 Script control.lua:516: stack traceback:
	__FARL__/control.lua:516: in function 'debugDump'
	__FARL__/control.lua:124: in function <__FARL__/control.lua:88>
	[C]: in function 'pcall'
	__FARL__/control.lua:88: in function <__FARL__/control.lua:87>
1570.906 Script control.lua:517: 6980667 Unexpected error: __FARL__/FARL.lua:2783: attempt to index field '?' (a nil value)
```

**Comment by Choumiko** [comment]
I'll have a fix out tomorrow, for now you should get away with either removing the concrete/stone paths from the blueprints or unchecking the option "place concrete" or making sure you have the stuff in the wagons.

On a side note: You don't need that many stone tiles in the blueprint, here are strings with the minimal amount to get a solid path:

> 0eNqdle1ugyAUhu/l/IZF8aOtt9IsC7UnLQmCUbqtabz3gTpXJ00IvwR934fzZXjASd6w7YQyUD1A1Fr1UB0f0IuL4tK9M/cWoQJhsAECijdu13EhYSAg1Bm/oUqHdwKojDACJ/+4uX+oW3PCzgoWZ2+s93I1dEQQaHVvXVq5oyyJMgJ397Dws+iwnr7tBrJhsoX5pfUZFa2v2BsPMn8rJqhdDB5QtkrLYrhQdC7Alpb+0uxiHWThYecL+yQuFKXVdqKmrZa4ZScz2Bdk8VfBhktJJW/aLWEJjvlTLYMoS46Jn7IL7ebUzIBe7tcteFX85CmuFTP1MA+B85HN0Mwla+fYCDkP8f+yzLV1Zy/5a4W05eYKLoLN5EUa8mBDFmnIgg0s0sCCDWmkIQ01JFH6JFSexsiDg2Ex8uBaZjHyF7Ng/53xlqieLhUCn9j1I6DMc1bs90V5KIfhBz6HFjk=

> 0eNqVlt1ugzAMhd/F16TiJwHKq0zTlFKrjRQCgnRbVeXdFyjr6IAN3xGwv3PsOCg3OOgLNq0yFoobqLI2HRQvN+jUyUjdv7PXBqEAZbGCAIys+lUrlQYXgDJH/IQicq8BoLHKKrznD4vrm7lUB2x9wCOzq6TWTMuq8bSm7nxKbXodj2HhTgRw9Q/RTjgXzDDxA/NR10c0rDxjZ+cg8Q8n+bFjfSmns2VDRXNHfOCESxD+1A1vRSrDxr7NQfG3JV+jb9xRtVjev/MFtniwD+rEUPvYVpWsqTUusKN1k+mzyTV74dTdAibb2rB43Uq+cfNYNppZ2bz9tlmKphQ/nlbpcTZ/R+bjrLhJkbVB1kh7ht7AckK4OT6jCmREgZQqkBIFBFVAEAU4VYATBRKqQEIUiKkCMVEgogpENIGQyA9peKp9ontq+4ndp44PcXqo40+cfurx/fP0+n/pcBkoJneHAN6x7QZAynks8lyk+9S5L+nysLc=

The wooden boxes should not be needed i think, FARL calculates a clearance area that includes all the entities + tiles (i think). They are only needed when you want extra empty space along the tracks.

**Comment by sgtsquiggs** [comment]
Great! I'll try this out

**Comment by Choumiko** [comment]
fixed since https://github.com/Choumiko/FARL/commit/8b8e14a704365434d88af2ad01870aff021a6a4e
