### ISSUE TITLE
Error while running event: LuaEntityProtoType doesn't contain key speed

### ISSUE THREAD

**Issue by KarelPeeters** [Choumiko/FARL#84]
I'm running the latest FARL version , 1.1.2. I consistently get the following error whenever I try to get inside a FARL train (even if it is newly-placed):

![image](https://user-images.githubusercontent.com/7887115/27458589-0fda74c0-57aa-11e7-806a-87dcfde72bdb.png)

I started this world with an older version of FARL, 0.5.x if I remember correctly, even though that didn't work, ie. it didn't register anything because that version was way to old.

**Comment by Choumiko** [comment]
Looks like you are using a version of Factorio < then 0.15.17.
Either update Factorio to at least 0.15.17 or use FARL 1.1.1

Let me know if it works or not, i can't reproduce it on the latest Factorio verison.

**Comment by KarelPeeters** [comment]
Yup, updating to 0.15.23 fixed the issue. Thanks a lot!
