### ISSUE TITLE
Desync picking up cargo wagon

### ISSUE THREAD

**Issue by Kuhnix46** [Choumiko/FARL#85]
A desync happens when the player picks up a cargo wagon after driving over stone rocks. The issue seems to be that if the probability of an item dropped by a stone rock is not 1, the server and clients generate a different set of items. 

Mods used:
Angel’s Refining (geodes in stone rocks)
Bobs Functions Library (dependency for Angels Refining)
Bobs Metals, Chemicals and Intermediates (dependency for Angels Refining)
FARL

After changing the probability on the geodes to 1, it works without a desync.

Steps to reproduce:
1.	Place track in front of a stone rock.
2.	Put FARL and cargo wagon on track with rails in the inventory.
3.	Driver over the stone.
4.	Get out and pickup wagon (Note the geodes in the wagon inventory)
5.	Desync
6.	Different geodes in player inventory

![farl-1](https://user-images.githubusercontent.com/10300116/27630202-11722f04-5bf5-11e7-8482-97eeed36a8ce.jpg)
![farl-2](https://user-images.githubusercontent.com/10300116/27630200-114f9110-5bf5-11e7-84bc-4d0c5057ba00.jpg)

After Desync:
![farl-3](https://user-images.githubusercontent.com/10300116/27630201-1169493e-5bf5-11e7-9c74-503ec9d384b3.jpg)

Desync Report:
[desync-report-2017-06-28_11-27-22.zip](https://github.com/Choumiko/FARL/files/1108190/desync-report-2017-06-28_11-27-22.zip)

**Comment by Choumiko** [comment]
Thanks for the report, should be fixed in 1.1.3
