### ISSUE TITLE
GUI setting changes not applied

### ISSUE THREAD

**Issue by pulzar** [Choumiko/FARL#92]
Starting with 16.19 or so, or a few days ago, I can't adjust any settings in FARL GUI. Anything I change doesn't "take" and FARL keeps working with previous settings. If I leave the engine and come back, I see the settings have reverted to the previous ones.

I tried deleting and re-installing the mod, but that just reset the settings to mod defaults, instead of the previous values I had a few days ago. 

I see that there was a change 8 days ago... now the mod has both settings.lua and Settings.lua... I'm not sure if that's the problem. Removing the lower-case settings.lua from the zip file didn't help.

Anyone else seeing this?

**Comment by stromnom** [comment]
Yes! I am having trouble with using the bridge water option. Same thing, when i try enabling it, I cant, whenever i press Start and start going, that option gets uncheck and it never places any bridges. I have been reading the code and I think that is the case with the same name of the file just in different case S. in windows, it doesnt let me keep two files with the same name, it doesnt accept the case change as a new file name. So i am guessing thats why its not working for me, atleast on windows 10 platform. As i need to have it in the zip format to keep both files, extracting removes one of those files. and I believe the settings cannot be stored while the file is in a zipped form.

**Comment by stromnom** [comment]
Just confirmed. with the two files having the same name... windows isnt even letting me save changes to the Settings.lua file manually.... I think just changing the name of the file (apart from just the case S) will be the easy fix to all this problem.

**Comment by pxanych** [comment]
Fixed by #93

**Comment by stromnom** [comment]
Yes it is fixed now! Thanks! i patched your commits into it myself to test. Just waiting for it to update officially soon! :D thnx pxanych!
