### ISSUE TITLE
Recent change causes conflict with Dectorio

### ISSUE THREAD

**Issue by jpanther** [Choumiko/FARL#95]
A recent commit (76137ae5cc654d8b123b310adac5bbf86b4c1559) reverted a fix that prevented FARL from picking up tiles when Dectorio is present in the same game. Originally the fix excluded Dectorio tiles based upon the tile name but I believe this change now looks at whether a tile is blueprintable to determine whether FARL should pick them up. The issue now arises as Dectorio allows players to toggle tiles as blueprintable and so this fix isn't working in all instances.

The way to prevent this is to re-introduce checking tiles by name here: https://github.com/Choumiko/FARL/blob/76137ae5cc654d8b123b310adac5bbf86b4c1559/FARL.lua#L980 and to test:
`and not string.starts_with(toPlace, 'dect-base')) and not string.starts_with(toPlace, 'dect-alien'))`

The reason this was reported as a bug against FARL was because the original test only checked for names starting with `dect-base` and this meant it didn't work for players who also played with Alien Biomes as Dectorio has tiles called `dect-alien-biomes-[name]` which were being missed by the more specific test condition.

If you have another preferred way of excluding tiles that doesn't rely on the blueprintable flag, I'm happy to modify the prototypes in Dectorio accordingly. For instance, it may be possible to exclude tiles that have an autoplace setting, that way it will ignore any landscape tiles from any source by default.

Ref: jpanther/Dectorio#70

**Comment by Choumiko** [comment]
Should also fix https://github.com/jpanther/Dectorio/issues/70
