### ISSUE TITLE
Farl breaks scenario loading

### ISSUE THREAD

**Issue by kylewill0725** [Choumiko/FARL#99]
Reproduce:
1) Make new scenario with map editor
2) Save scenario
3) Load scenario
4) Scenario fails to load
5) Disable farl
6) Scenario loads successfully

Error text from factorio-current.log:

> 46.062 Failed to deserialize mod data for "mod-FARL". Error: Deserialization error, LuaObject targets to wrong object. Save file is probably corrupted.
> 46.107 Error AppManagerStates.cpp:1426: Failed to load saved data for following mods: 
mod-FARL

Displayed error:
![image](https://user-images.githubusercontent.com/18157392/53684428-e7b97300-3cd2-11e9-9aca-504a1c6ad88c.png)

Workaround: Disable farl, load scenario, place a locomotive down, and save scenario. Now the save will work with farl enabled.

**Comment by Choumiko** [comment]
Reported as a bug here: https://forums.factorio.com/viewtopic.php?f=29&t=66812

**Comment by Choumiko** [comment]
fixed (worked around to be precise) in 998514783bb6dfdb3b628654b1c6a0937e054be4

Luckily the saved LuaObject wasn't used
